services:
  bot:
    container_name: discord_toy_bot
    build: ..
    env_file:
      - .env
    environment:
      UV_PROJECT_ENVIRONMENT: /venv # create virtual environment in /venv inside the container
    volumes:
      - type: bind
        source: ../src
        target: /app_root
    working_dir: /app_root
    tty: true
    stdin_open: true
    command: uv run app.py
    restart: always
